import React, {  } from "react";
import Image from "next/image";
import Head from "next/head"; 
import Link from "next/link";

import Typography from "@mui/material/Typography";
import {Box, CardActionArea, CardContent, Grid,Skeleton } from "@mui/material";
import SearchIcon from '@mui/icons-material/Search';

import { cardlogo } from "../../assets/images";
import SideBarComponent from "../../components/sideBar/sideBarComponent";

import HomeController from "./home.controller";
import { BotCard, BotCardLogo, BotCardTitle, HeaderTitle, PageHeader, Search ,SearchIconWrapper,StyledInputBase} from "./home.style";

export default function Home() {
  const { getters, handlers } = HomeController();
  const {bot,loading, searchText, searchResults}=getters;
  const { fetchData,handleSearch } = handlers;
  const itemsToRender = searchText.trim() === '' ? bot : searchResults;
  const placeholderData = Array.from({ length: 12 }, (_, index) => index);
  return (
    <>
      <Head>
        <title>ChatBot App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBarComponent>
        <>
            <PageHeader >
               <HeaderTitle >
            <Typography
              gutterBottom
              variant="h6"
              component="div"
              align="center"
              style={{
                fontWeight: 700
              }}>
              BOT
            </Typography>
             </HeaderTitle>
            <Search >
            <SearchIconWrapper>
              <SearchIcon />
            </SearchIconWrapper>
            <StyledInputBase
            value={searchText}
            onChange={handleSearch}
              placeholder="Search…"
              inputProps={{ 'aria-label': 'search' }}
            />
          </Search>
            </PageHeader>
            <Box>
              <Grid container spacing={3}>
                {loading? placeholderData.map((index) => {
                  return(
                     <Grid item key={index} xs={12} sm={6} md={4} lg={3}>
                       <BotCard key={index}>
            <CardContent>
              <Skeleton align="center" variant="circular" width={85} height={85}/>
              <Skeleton variant="text" width={295} height={30} />
            </CardContent>
          </BotCard>
                      </Grid>
                  )
        }):itemsToRender.map((bot, index) => {
                  return (
                    <Grid item key={index} xs={12} sm={6} md={4} lg={3}>
                      <Link href={`/bot/${bot._id}`} style={{textDecoration:"none"}}>
                        <BotCard>
                          <CardActionArea>
                            <BotCardLogo>
                              <Image
                                src={cardlogo.src}
                                alt={"Card Logo"}
                                width={cardlogo.width}
                                height={cardlogo.height}/>
                            </BotCardLogo>
                            <CardContent>
                              <BotCardTitle
                                gutterBottom
                                variant="h6"
                                align="center">
                                {bot.name}
                              </BotCardTitle>
                            </CardContent>
                          </CardActionArea>
                        </BotCard>
                      </Link>
                    </Grid>
                  );
                })}
              </Grid>
            </Box>
        </>
      </SideBarComponent>
    </>
  );
}
 
