export { default as SignInBg } from "./SignInBg.png";
export { default as SignInBg2 } from "./bgpic1.png";
export { default as mindpathIcon } from "./mindpath-icon.png";
export { default as signupPic } from "./signup-pic.png";
export { default as logoColored } from "./logocolored.png";
export { default as menuItemlogo } from "./drawerpng.png";
export { default as ebotifylogo } from "./ebotifylogo.png";
export { default as cardlogo } from "./cardlogo.png";
export { default as userpic } from "./userpic.png";
export { default as estateBot } from "./morganrandall.png";
export { default as nodatafound } from "./nodatafound.svg";
export { default as webBot } from './webBot.png';
export {default as whatsapp} from './whatsapp.png';
export { default as facebook } from "./facebook.png";
export { default as telegram } from "./telegram.png";
export { default as login } from "./login.png";