import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import { reactionIcon, tagIcon } from "../assets/images";

export default function Posts() {
  const [posts, setPosts] = useState([]);
  useEffect(() => {
    fetch("https://dummyjson.com/posts")
      .then((response) => response.json())
      .then((data) => setPosts(data.posts))
      .catch((error) => console.error("Error fetching data:", error));
  }, []);
  const postsByUserId = posts.reduce((acc, post) => {
    const { userId } = post;
    if (!acc[userId]) {
      acc[userId] = [];
    }
    acc[userId].push(post);
    return acc;
  }, {});

  return (
    <>
      <Head>
        <title>All Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        display="flex"
        flexDirection="column"
        alignItems="center"
        sx={{ padding: 2, bgcolor: "rgb(11, 15, 25)" }}
      >
        <Typography
          gutterBottom
          variant="h6"
          component="div"
          align="center"
          style={{
            color: "white",
            fontSize: 30,
            fontWeight: 900,
            textOverflow: "ellipsis",
          }}
        >
          All Posts
        </Typography>
        {Object.keys(postsByUserId).map((userId) => {
          return (
            <Box
              item
              key={userId}
              sx={{
                bgcolor: "rgb(234 255 223)",
                borderRadius: 4,
                width: "85%",
                marginBottom: 2,
                padding: 2,
              }}
            >
              <Typography
                variant="h6"
                align="center"
                style={{
                  fontSize: 24,
                  fontWeight: 700,
                }}
              >
                User Id: {userId}
                &nbsp;
                <Box
                  sx={{
                    textAlign: "left",
                    fontSize: 15,
                    fontWeight: 700,
                  }}
                >
                  {postsByUserId[userId].map((post) => (
                    <div key={post.id}>
                      <div //i have used this div to align Title and Post Id in one line using display flex
                        style={{
                          display: "flex",
                          justifyContent: "space-between",
                        }}
                      >
                        <div style={{ fontWeight: 900, fontSize: 20 }}>
                          Title: {post.title}
                        </div>
                        Post Id: {post.id}
                      </div>
                      <p>{post.body}</p>
                      <Box
                        style={{
                          display: "flex",
                          fontWeight: 700,
                          alignItems: "center",
                          fontSize: 13,
                          paddingBottom: 5,
                          color: "#383535",
                        }}
                      >
                        <Image
                          src={tagIcon}
                          width={24}
                          height={24}
                          alt="tag icon"
                        />
                        &nbsp;
                        <Box>{post.tags.join(", ")}</Box>
                      </Box>
                      <Box
                        style={{
                          display: "flex",
                          fontWeight: 700,
                          alignItems: "center",
                          fontSize: 13,
                          color: "#383535",
                        }}
                      >
                        <Image
                          width={24}
                          height={24}
                          src={reactionIcon}
                          alt="reaction icon"
                        />
                        <Box sx={{ paddingLeft: 1 }}>{post.reactions}</Box>
                      </Box>
                      <hr />
                    </div>
                  ))}
                </Box>
              </Typography>
            </Box>
          );
        })}
        ;
      </Box>
    </>
  );
}
